### ISSUE TITLE
Safari scroll issue

### ISSUE THREAD

**Issue by html5cat** [elrumordelaluz/reactour#10]
When scrolling the page content scrolls but the tour popup and mask stay in the same spot of the window.

Safari: Version 10.1.1 (12603.2.4)
MacOS: 10.12.5 (16F73)

Awesome project! Love tours :)

**Comment by elrumordelaluz** [comment]
Hi @html5cat,
Unfortunately I am on _Safari_ `Version 10.1.1 (11603.2.5)` on _OSX El Capitan_ `10.11.6`, but tested on the same browser and os versions you provide through [Cross Browser Testing](https://crossbrowsertesting.com/) and didn't see the issue.

Can you show a video/gif to understand better?

**Comment by html5cat** [comment]
Sure! Here’s a video from safari on iOS 11 beta, but same effect in safari on Mac for me:
https://www.dropbox.com/s/kizupprw6s3i3kt/File%20Jul%2005%2C%209%2046%2016%20PM.mp4?dl=0

**Comment by elrumordelaluz** [comment]
Thanks @html5cat ! Now I understand what you mean. 

_Reactour_ doesn't observe `scroll` events so, by default [is applied](https://github.com/elrumordelaluz/reactour/blob/master/src/TourPortal.js#L48-L53) an `overflow` rule on `body` when the _Tour_ is active, using `onAfterOpen()` and `onBeforeClose()` [props](https://github.com/elrumordelaluz/reactour#proptypes) not allowing the user to scroll. You could obviously override both methods as you want/need.

I think the issue is related on that _Safari_ (also the version have) applies `overflow-y` in the `body` only if is declared also `overflow-x`. Don't know why 😐

**Comment by elrumordelaluz** [comment]
I am trying to replace [`overflowY`](https://github.com/elrumordelaluz/reactour/blob/master/src/TourPortal.js#L49) into `overflow` and it works in _Safari_ but brake the _Tour_ basic behaviour in _Firefox_.

In case you came to a fix or at least a custom solution, PR are super welcome!
Thanks again,

**Comment by html5cat** [comment]
Gotcha. Let me think about it. Maybe one option is to go around and have the user being able to scroll but keep the position of tooltip above the element. But that requires a bigger refactor :)

**Comment by elrumordelaluz** [comment]
No problem about a bigger refactor. The point on follow when the user scrolls is the performance observing scroll events. At first time I thought a light solution is to _block_ the scroll and only set by default resize events.

**Comment by elrumordelaluz** [comment]
Issue fixed using [body-scroll-lock](https://github.com/willmcpo/body-scroll-lock) in the [demo](https://github.com/elrumordelaluz/reactour/blob/master/src/demo/App.js#L55-L56)
