### ISSUE TITLE
Disable a single element

### ISSUE THREAD

**Issue by gdsrosa** [elrumordelaluz/reactour#114]
Scenario: I have two buttons inside the Tour mask and I want to disable one of them. 
Question: It is possible @elrumordelaluz?

**Comment by elrumordelaluz** [comment]
Hi @gdsrosa, 
Could be an interesting feature but have to make some tricks with the `svg` mask. However right now you could do something with the `step.action` prop, something like: 

```js
const steps = [
  {
    selector: '.a',
    action: elem => elem.querySelector('button:last-of-type').setAttribute('disabled', true)
  }
]
```

It's a little tricky since you have to remember to enable again when _Tour_ will close. This let me know in another possible _feature_ to have `actions` something like `beforeStep`and `afterStep` (with better naming) to fully control what you want with the target element. related #102

**Comment by gdsrosa** [comment]
Thanks for the solution @elrumordelaluz, I resolved this issue with another way, in my case I used the data that was in redux and pass via props through my Tour component and applied some rules.

**Comment by gdsrosa** [comment]
I will close this issue!
