### ISSUE TITLE
Great library! Mask Question and General Feedback

### ISSUE THREAD

**Issue by bmoquist** [elrumordelaluz/reactour#14]
Thanks so much for making this great library! I’m using it with Redux for a product tour of a canvas-based application. Things generally worked great out of the box. 

Regarding the mask, is there a proper way to turn it off?

For my tour, the user needs to interact with the page while the tour goes on.  I re-enabled scrolling by removing the default from the onAfterOpen property, and I disabled the mask by setting maskClassName to: 
```css
.tourMaskStyle {
  position: absolute;
  z-index: -100;
  background-color: transparent;
}
```
No worries if not —  such a maskOn prop could be a good future addition.

If you're open to it, some general feedback:
- I love the action property in each step as I’m able to pass in Redux actions that set-up aspects of the tour for the user.

- Everything flows really nicely and smoothly on interaction with the tour box - impressively done!

- Adding some more properties at the step-level might be useful such as being able to offset the step in a certain x, y, direction vs. globally for all steps. In my case, I tried to position the tour box in a specific spot (partially over the large canvas element) so the user would be able to see the display better.  I initially intended to limit the user's interaction to that of the bounding box, but the approach wasn't flexible enough for my needs given how the step and canvas were being displayed. I didn't find a great solution with the offset property so I ended up disabling the mask and re-enabling the scroll, which actually ended up working really nicely.

- Could you explain how inViewThreshold would be used and/or give an example? I played with it but didn’t see any results by changing the threshold.

- Consider clarifying the word ‘helper’ for className prop documentation. It seems to be the Tour Guide pop-up box after experimenting with it.

- scrollDuration units are in milliseconds?

- Consider adding some more keywords to your npm package so it’s easier to be found. I tried out several other libraries before coming across reactour. I liked your work the best! Some additional keywords could include: onboarding, on-boarding, walkthrough, walkthru, product-tour, redux, joyride, hopscotch, and shepard. 

Hopefully, the above can be useful --- thanks for all your hard work on this library! 
Bryant

**Comment by elrumordelaluz** [comment]
hey @bmoquist first of all thanks for the kind words related on _Reactour_, really pleasured that you like it and mostly that is useful for your _Application_.

Let me walkthrough to reply all the points.

**Turn off the mask**
For now there isn't an official way to turn off the _Mask_ via `props`.
I'd do something (similar to your workaround) like:
```js
<Tour
  onRequestClose={() => …}
  steps={[ … ]}
  isOpen={true}
  maskClassName="mask"
/>
```
```css
.mask { display: none }
```

Honestly I didn't think on it as an option by lacking of necessity but your _use-case_ it's super valid one to think on it.
Maybe we could open another issue (and PR related in case) only for this _feature_ to ask/analyse deeply, for example, if it is really necessary since there is a way to launch the _Tour_ without _Mask_ and `overflow` behaviours. Meanwhile thanks for the hint!

---

> I love the action property in each step as I’m able to pass in 

♥️

> Everything flows really nicely and smoothly on interaction with the tour box

The magic is thanks to `styled-components` and `css` transitions/transforms that are pretty smooth these days in _browsers_

> Adding some more properties at the step-level might be useful…

Absolutely true! Love the idea. Let me think and analyse this point in detail to work on it. Also PR welcome!

--- 
yes, I know, [I have to take time to improve](https://github.com/elrumordelaluz/reactour/issues/11#issuecomment-325687972) (interactive?) _docs_ and made more examples. Also PR welcome™ 😃

Regarding `inViewThreshold` is a number to sum to the window _view_ limits (top, right, bottom, left) to make the step `elem` _scrollTo_ the center. The default is `0` so, only if part of the `elem` is outside the window, the _Tour_ make scrolls it to the center. If I set `inViewThreshold={100}`, the _Tour_ will scroll the `elem` when is at least at `100px` to the limits.

Below both examples, the first one with the default value (0), the second one with value 100.

![inview_1](https://user-images.githubusercontent.com/784056/30429174-c8c427c2-9956-11e7-88f1-9a7971b912f9.gif)

![inview_2](https://user-images.githubusercontent.com/784056/30429176-cd3c38b2-9956-11e7-969d-a70204e5e17e.gif)

> Consider clarifying the word ‘helper’

yes, **helper** is the _pop-up_ there are better word to describe it, right?

> scrollDuration units are in milliseconds? 
yes, milliseconds to pass to `scroll-smooth` pack

Will add more `npm` tags, thanks!

Thanks for all the inputs @bmoquist appreciate so much!

**Comment by bmoquist** [comment]
Appreciate the detailed response! 

- Your CSS solution is much better/less hacky for turning off the mask than mine --- think that is simple enough for me vs. a prop.

- Got it on inViewThreshold. Basically, if the (target element + inViewThreshold position on each side) falls outside of the viewing window, then Reactour will re-center the view such that the whole element is visible.

- Helper has many meanings and is pretty overloaded in computer science (e.g. helper functions). Consider something a bit more specific --- Tour Popup, Tour Guide Popup, Tour Box, Tour Guide Box...

Thanks for all of the help and work you've put in on this! Great job!
Bryant

**Comment by elrumordelaluz** [comment]
thanks again for the inputs @bmoquist!
