### ISSUE TITLE
Scroll inside container

### ISSUE THREAD

**Issue by Justinger** [elrumordelaluz/reactour#141]
Hey,
i need the option to scroll inside a div which is not the body. Is there a solution/workaround?

**Comment by elrumordelaluz** [comment]
Hi @Justinger, thanks for open the _Issue_.

The [step 8](https://github.com/elrumordelaluz/reactour/blob/master/src/demo/App.js#L227-L230) in the [demo](https://reactour.js.org/) shows the scroll behaviour for an `fixed` positioned element for example. 

Is something like this what you mean? Otherwise, could you please provide more info of your use case or better a [codesandbox](https://codesandbox.io/s/6z56m8x18k?module=%2FApp.js).

**Comment by Justinger** [comment]
I tryed to adapt the styles of your scrollable component to my project, but it didnt seem to work. 

Here is a quick gif what describes my problem:
![screen](https://user-images.githubusercontent.com/51965901/59745673-98915100-9275-11e9-89ed-05d97d783749.gif)

If an element is outside my viewport, the container does not scroll down.
My scrolling container got the styles:
`display: flex;
flex-direction: column;
flex: 1 1;
overflow-x: hidden;
overflow-y: auto;
-ms-overflow-style: -ms-autohiding-scrollbar;
-webkit-overflow-scrolling: touch;
position: relative;`

**Comment by elrumordelaluz** [comment]
Ok, I think the problem is related on the _offset threshold_ which could be controlled throygh [inViewThreshold prop](https://github.com/elrumordelaluz/reactour#inviewthreshold). However with the _default_ value shuold scroll to center also when part of the element is outside. Mind creating a simple reproduction in a codesandbox?

**Comment by Justinger** [comment]
I will try to create a reproduction.

**Comment by Justinger** [comment]
I was able to reproduce the issue :)

https://codesandbox.io/embed/reactour-demo-template-tlpix

**Comment by elrumordelaluz** [comment]
awesome, I'll give it an eye and back to you soon

**Comment by Justinger** [comment]
Great, thank you 👍

**Comment by Justinger** [comment]
Hey, 
did you take a look into my example?

**Comment by elrumordelaluz** [comment]
hey @Justinger, I'm sorry for the delay.
yes, I did and found the _issue_ is related on `scroll-smooth` module. I am trying to fix that asap.

**Comment by Justinger** [comment]
Ok great. Thank you :)

**Comment by elrumordelaluz** [comment]
hey @Justinger,
going deep into the _issue_ noted that is not related on the _scroll behaviour_ but in the analysis of _scrollable parent_. This part of `reactour` is useful to allow scroll/appear parts of the _Document_ hidden or scrolled inside `elements` outside the main scrollable area (`html`/`window`). 
That process use [scrollparent](https://github.com/olahol/scrollparent.js) library that check _styles_ related on `overflow` etc. 

Take a look at [this fork](https://codesandbox.io/embed/reactour-demo-template-b5q2e) with comments on 4 lines of the `css` that make the _Tour_ works properly. 

Please let me know if that lines of `css` are fundamental and in that case we need to analyses similar use-cases. As far as I understand, and at least in the demo reproduction, those containers doesn't scroll by itself, so the scrolling element is `html`/`window`.

**Comment by Justinger** [comment]
Hey,
i dont know if i just missed the fact, that the reproduction did not scroll or if it is a new behavior. 

The fix does not fit my needs. I need the app frame (sidebar / header) to be static. I only want to scroll inside the "App-pageContent".

I played with the editor and magicaly got it working....
https://codesandbox.io/s/reactour-demo-template-if091?fontsize=14

The only issue left is the scrollbar which appears after i finish the tour. But i guess this is something inside my app.
I will try to port the settings from the sandbox into my project. 

Thank you for your help :)

**Comment by elrumordelaluz** [comment]
Cool that now works as expected! Hope you could reproduce that in your project.

**Comment by Justinger** [comment]
I was not able to fix it inside my pproject yet.
Maybe i can explain my problem better now.

![IMG_20190626_153214](https://user-images.githubusercontent.com/51965901/60184187-e125ad00-9827-11e9-9e9e-0ff8a5a2f4f5.jpg)

I got a div (red) which allows to scroll. 
Inside this div there is another div (dotted) which represents the grid of my content. The grid is not limited in height and contains a div (yellow). Inside the yellow div is another div (not marked in the pic) and inside this last div, there are the targets of the tour. 
If i navigate the tour to one item (outside the viewport), the mask travels to the specific position, but the red div does not scroll. 

If i remove the grid (dotted), the yellow div shrinks to fit inside the red. I now have two scrollbars. The red one and the yellow one. If I navigate to an element outside the viewport, the yellow div scrolls.  

Isn't it possible to define the ref which should get scrolled? Maybe that would fix the problem.

**Comment by elrumordelaluz** [comment]
Is the `red` div `position: fixed`?

Can we update the intial _sandbox_ to make tests there?

**Comment by Justinger** [comment]
the `red` div got the props:
`display: flex;
flex-direction: column;
flex: 1 1;
overflow-x: hidden;
overflow-y: auto;
-ms-overflow-style: -ms-autohiding-scrollbar;
-webkit-overflow-scrolling: touch;
padding-top: 1rem;
position: relative;`

The `red` div is the class `App-pageContent` inside the initial sandbox. The `dotted` div got the class `App-pageContentScrollcontainer justify-content-center`.

**Comment by elrumordelaluz** [comment]
@Justinger What _sandbox_ can I use as a starting point, since [the first one](https://codesandbox.io/embed/reactour-demo-template-tlpix) doesn't scroll (but the _Header_ scrolls, and the opposite on [the last one](https://codesandbox.io/s/reactour-demo-template-if091?fontsize=14), scrolls, and the _Header_ is `fixed` positioned.

**Comment by Justinger** [comment]
Sorry for the delay. 
I finally got a working example here: https://codesandbox.io/embed/reactour-demo-template-owb55
Unfortunate the tour works perfectly inside the sandbox. I copyed all styles exactly and dont know why the tour does not work inside my project.

**Comment by elrumordelaluz** [comment]
I see something similar reproducing one of your examples in my local environment and arrived that I missed to copy the wrapper `.App` and its _styles_ like in the sandbox; make sure you are maintaining also this `div`, otherwise I don't know what could happen.

Regarding the _issue_, the behaviour of the _sandbox_ is the desired one, right? Feel free to close it, or ask more info in any case.

**Comment by Justinger** [comment]
Yep, i missed the `styles.css` in my sandbox too.

The sandbox now works as dessired. 
I am still trying to get it to work inside my project, but thats not an issue with reactour. 
Thanks for your help :)
