### ISSUE TITLE
Delay per step transition?

### ISSUE THREAD

**Issue by RobertGary1** [elrumordelaluz/reactour#148]
Is there anyway I could add a delay for a particular step? It needs to wait for a react component to build.

**Comment by elrumordelaluz** [comment]
Hi @RobertGary1, thanks for open the _Issue_. Could you please elaborate a little more what do you mean with:

>  It needs to wait for a react component to build.

thanks,

**Comment by RobertGary1** [comment]
I have times when the component I want to highlight isn't quite yet rendered because its waiting on backend data. If the tour highlights it too soon it doesn't seem to update once its rendered.

**Comment by elrumordelaluz** [comment]
You have to use the `update` prop on _Tour_ component, when the value passed down to that prop changes, forced an update so the _Helper_ takes the right position.

**Comment by RobertGary1** [comment]
Thanks.

**Comment by aqarain** [comment]
@elrumordelaluz I didn't get this. Can you please elaborate?
My scenario is when I go back from one route B to route A, the rendering of data of view takes a little time on that view but the guided tour card shows up instantly and it shows up at the wrong place.
Can you please suggest how to overcome that problem?

**Comment by RobertGary1** [comment]
I've create a PR 184 https://github.com/elrumordelaluz/reactour/pull/184 to address this.

**Comment by baohouse** [comment]
The problem with using `update` and `updateDelay` to force a render is when there is a moving element. In my scenario:

1. Element is offscreen on the left, and transitioning towards the center.
2. Tour highlight boundary is on the left of the page.
3. Element is centered on the screen after 300 ms
4. I set my updateDelay to 325ms, and the tour highlight boundary moves from left to center.

The experience is a little jarring; I think it makes sense for #184 to delay rendering the next tour card so that my element is in the final position before being highlighted.
