### ISSUE TITLE
Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.

### ISSUE THREAD

**Issue by albertogaldames** [elrumordelaluz/reactour#159]
Hey, congrats for the great project.

I'm getting this annoying message in the console when I try to put a custom Button component as the lastStepNextButton property (in my case I'm passing the [Material-ui Button](https://material-ui.com/components/buttons/) component

`Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.`

In the DOM I can see the custom Button is rendering inside the Button of the last next button. Shouldn't it be the button I passed through the prop?

This is my configuration:
```
<Tour
        steps={steps}
        isOpen={isTourOpen}
        onRequestClose={closeTour}
        accentColor={accentColor}
        scrollDuration={300}
        disableInteraction={true}
        lastStepNextButton={<Button color="primary" size="small">Ok, lo pillo</Button>}
        rounded={5}
        onAfterOpen={disableScroll}
        onBeforeClose={enableScroll}
/>
```

**Comment by elrumordelaluz** [comment]
Hi @albertogaldames, thanks for open the _Issue_. I am happy you are enjoyng the _Tour_.

At the moment the `lastStepNextButton` pass a _String_ inside the _Arrow_ (which is a `button`) to render the text (for example "finish!") instead of the -> arrow. However you could use a [custom Component](https://github.com/elrumordelaluz/reactour/issues/157#issuecomment-519078951) and handle this and other situations.

**Comment by albertogaldames** [comment]
Ah, ok perfect. Is this something you have in mind to implement? I mean the documentation says it accepts a `node` type and the example seems to be a custom button component.

```
// example
<Tour lastStepNextButton={<MyButton>Done! Let's start playing</MyButton>} />
```

**Comment by elrumordelaluz** [comment]
Oh you are absolutely right, need to fix the _Docs_.
