### ISSUE TITLE
I can't write on inputs

### ISSUE THREAD

**Issue by cFarreronsLopez** [elrumordelaluz/reactour#209]
When my step is on a input i can't write on this input text

![imagen](https://user-images.githubusercontent.com/57130776/69417328-c133e000-0d18-11ea-9027-9aff92b5a104.png)

**Comment by elrumordelaluz** [comment]
Hi @cFarreronsLopez, thanks for open the _Issue_.

Do you have a reduced reproduction? In case you are using an external components _library_, could you create/modify a [sandbox](https://codesandbox.io/s/6z56m8x18k?module=%2FApp.js) in order to _debug_ what could happen together?

**Comment by burnhamrobertp** [comment]
...I am aghast that this issue is open, its a simple documentation issue that could have helped this user months ago.

For anyone who comes upon this, check the Readme under the [Steps Shape](https://github.com/elrumordelaluz/reactour#steps-shape) and [Steps Example ](https://github.com/elrumordelaluz/reactour#steps-example) headers and you'll see an `action` function that looks like this:

```
  action: node => {
    node.focus();
  },
```

Add that to any step where the **target** of the step (i.e. the element in the `selector`, or any child of that element) has elements which need to be able to be focused in order to work correctly. I'm not talking about things like buttons or links; those are immediate and do not require focus. A text input field, however, does need focus in order to work.

Reactour uses `react-focus-lock` to lock focus to elements inside the **tour step**, so long as the tour is showing. Any time any element outside of the current step tries to be given focus, reactour redirects the focus back to the current step. The above "action" function transfers focus over to the targeted node.

**Comment by elrumordelaluz** [comment]
cool @burnhamrobertp, thanks for the input! mind make a PR to help _Docs_ in this specifc issue?

**Comment by GainiK** [comment]
I still have the issue of not being able to edit text fields. I added the

action: node => {
        // by using this, focus trap is temporary disabled
        node.focus()
        console.log('yup, the target element is also focused!')
      },
It prints 'yup....', but nothing can be entered into text field.

**Comment by elrumordelaluz** [comment]
@GainiK do you have a reduced reproduction to inspect or a codesandbox?

**Comment by tiagopmc** [comment]
@elrumordelaluz I`m still having the same problem. I do `node.focus();`and I can not write on the text field

**Comment by tiagopmc** [comment]
@elrumordelaluz I just read your code, If I use `disableFocusLock` set as `true`to `<Tour>`I can fix this problem.

**Comment by elrumordelaluz** [comment]
@tiagopmc most of the times the _issue_ is related on an undesired re-render of the _Tour_ Component. Do you have a reduced reproduction to put in a sandbox?

**Comment by cherishh** [comment]
> @elrumordelaluz I just read your code, If I use `disableFocusLock` set as `true`to `<Tour>`I can fix this problem.

Come across with the same issue. But in my case there is another input field in the next step, and somehow `node.focus()` from last step still working, so my step mismatch to the input field instead of the correct element.
Is there any way to fix this?

**Comment by elrumordelaluz** [comment]
hi all, any way to create a minimal reproduction i a sandbox? thanks!

**Comment by Sirius-Coder** [comment]
> @elrumordelaluz I just read your code, If I use `disableFocusLock` set as `true`to `<Tour>`I can fix this problem.

Thanks ! a lot ..It worked for me ...Literally spent hours looking for this

**Comment by sorokin-vladimir** [comment]
> @elrumordelaluz I just read your code, If I use `disableFocusLock` set as `true`to `<Tour>`I can fix this problem.

@tiagopmc  Thanks a lot! It works.
@elrumordelaluz I suggest you include this option into your official doc. It's such useful parameter

**Comment by IgorSousaFront** [comment]
> Thanks a lot! It works.

Thanks a lot! It works.
