### ISSUE TITLE
DISABLE TOUR WHEN KEYBOARD CHARACTER "K"  IS PRESSED 

### ISSUE THREAD

**Issue by rubimbura** [elrumordelaluz/reactour#225]
Some one help me on  how to disable the tour when someone clicks on keyboard on letter  "K".
It is annoying when some one tries to type starting with character k, the tour pops up immediately. 

Thanks!

**Comment by elrumordelaluz** [comment]
Hi @rubimbura, thanks for open the _Issue_.

Seems that you copy/pasted the code from the [Demo](https://github.com/elrumordelaluz/reactour/blob/master/src/demo/App.js#L26-L29).

**Comment by rubimbura** [comment]
Hi @elrumordelaluz  

 How is that relevant to my question?

**Comment by elrumordelaluz** [comment]
Hi @rubimbura, maybe I misunderstand your point.

> It is annoying when some one tries to type starting with character k, the tour pops up immediately.

Are you talking about the [demo](https://reactour.js.org/) or your own _Application_?

**Comment by rubimbura** [comment]
Hi @elrumordelaluz 
i developed my application and added This reacttour, now the problem is when I click letter K the tour pops up. Is there any way to disable it when I click character K.

**Comment by elrumordelaluz** [comment]
hi @rubimbura thank you for the clarification.

I supposed that when wrote you 
> Seems that you copy/pasted the code from the Demo.

Because the part I [linked you](https://github.com/elrumordelaluz/reactour/blob/master/src/demo/App.js#L26-L29), in specific the function `keyHandling` in the `src/demo/App.js` file has the only purpose of debug in the _Demo_ of the library. 
In the [demo](https://6z56m8x18k.csb.app/) made as a [sandbox](https://codesandbox.io/s/6z56m8x18k?module=%2FApp.js) to edit and play around, that function it isn't present and that _keyHandling_ behaviour doesn't happens. 
Keep in mind that the basic usage is shown in the [readme](https://github.com/elrumordelaluz/reactour#usage), all the other stuff is application-side.

I am closing here the _Issue_, since is not related to _Reactor_ but feel free to re-open or open another one in any case.

**Comment by rubimbura** [comment]
Hi @elrumordelaluz 
Thanks alot, I disabled keyHandling function
