### ISSUE TITLE
How to make the selected component area bigger?

### ISSUE THREAD

**Issue by iooops** [elrumordelaluz/reactour#230]
Could I add more space to its bottom?

**Comment by elrumordelaluz** [comment]
Hi @iooops, thanks for open the _Issue_.

You could use [maskSpace](https://github.com/elrumordelaluz/reactour#maskspace) for that purpose but increases the space proportionally.

**Comment by iooops** [comment]
I want to do it for a single component.

**Comment by ketewan** [comment]
Hello! Thank you for the library, it's really great!

I also need this feature: like having an ability to specify different padding/margin for each step. 

Moreover, I think it would be great to separate distances from target to mask border and from mask border to helper, which are now both equal to maskSpace, if I am not mistaken. I think distance from mask border to helper could be set with some extra "helperMargin" property.

I could try to do this and open a PR, if my suggestions are appropriate and my help is appreciated.

**Comment by elrumordelaluz** [comment]
Hi @ketewan, super welcome PR's and pretty appreciate your inputs. Thanks!

**Comment by ketewan** [comment]
@elrumordelaluz, what do you think, could there be added some extra logic on enabling/disabling padding interaction? So that only target without mask space or padding is active? I need it in my case (and have done by simply disabling the padding in all cases), but I'm not sure whether and how could it be done in common case. Like adding extra prop to control it? (disableSpaceInteraction?)

**Comment by farrukhayazqazi** [comment]
@elrumordelaluz any updates on the issue?

**Comment by elrumordelaluz** [comment]
Separated _Mask_ and _Popover_ spaces are now available in **new v2 version** released under scoped `@rectour` package name, please try `npm i @reactour/tour`. Every feedback super welcome, thanks!
