### ISSUE TITLE
How can we collaborate better and speed up development on this project?

### ISSUE THREAD

**Issue by nelsonwong1012** [elrumordelaluz/reactour#283]
This is a great project but I feel the speed of development and improvements is losing momentum. I think others agree with me. @elrumordelaluz, I'm sure you're busy with a lot of things. So I'm wondering what we can do to improve collaboration and make it easier for others to contribute. Just want to get this conversation started.

**Comment by elrumordelaluz** [comment]
Hi @nelsonwong1012!

I really appreciate your words and the fact that you open this _Issue_! 

First, because based on your activity on the project, I am pretty sure you appreciate it and the most important part, you use it! I am also aware that lots of the increasing _Issues_ are absolutely solvable in a better timing than the current one, which depends a lot in my activity or absence in the _repo_.

I'll put some points that I consider are blocking more that helping the project development. On the other hand, if you are agree I could add you as a _Collaborator_ to improve the flow.

### Basic updates and the `branch` issue

Some time ago I started to transform the _Tour_ using `hooks` instead of _Class_ methods and so on, to improve some parts and to port the project in the way I am using `react` nowadays. In this transition I put some constraints that I think only helped to reduce the maintaining flow of the project. Those things are:

- move the current version into `v1 branch` and develop in `master`
- expect to have `actionBefore` as a _must_ feature to publish the next major version

I know that you are aware of the second point and as a recap for others, my idea was that each `step` could have the ability to fire an `action` before and after land, both navigating with arrow, or directly to the `step`, avoiding extra calculations on where the _user_ come from before the desired `step` and so on. This feature could be useful for lots of _issues_ open where the user want to make the step _waitFor_ before show it or update the content after something happens in the background. The problem comes when the `async` action  is happen and the _user_ try to change `step`, how to cancel the `action` etc etc.

So as first two steps I think we could
- [ ] Check all the missing features that `master` is missing from `v1`
- [ ] Publish the `master` branch as a new major version, leaving aside the `actionBefore` issue for the moment

To then focus in the main topics that are requested in the _issues_, so:

- [ ] step actions
- [ ] make the _Tour_ work in _Modals_
- [ ] _Tour_ customizations (that is in part some docs for `CustomHelper` and improve some parts)
- [ ] improve _Docs_
- [ ] fix `observer` and `scroll` issues


Again, thanks for the great idea and apologize to all the ones that open an _Issue_ and expect a faster activity I couldn't guarantee in this moment. 

Let's make a better _Tour_ together :)

**Comment by haxxxton** [comment]
Just to throw my hat in this ring, i would love to help where i can, this project is awesome

**Comment by elrumordelaluz** [comment]
**v2** released under scoped `@rectour` package name, please try `npm i @reactour/tour`. Every feedback super welcome, thank you all!
