### ISSUE TITLE
[Feature Request] ability to defined custom SVGMask component

### ISSUE THREAD

**Issue by haxxxton** [elrumordelaluz/reactour#298]
It would be great to have the ability to define a CustomSVGMask. Particularly to allow for things like step specific rounding, rounding only in particular corners, custom shaped masks.

**Comment by MJeorrett** [comment]
A use case I have for this is an element which is out of the main document flow and so reactour's default mask, understandably, ignores it.

**Comment by elrumordelaluz** [comment]
Hi @haxxxton, thanks for open the _Issue_. Pretty interesting that _feature request_. Mind share at least a screenshot or a sketch with an example of what kind of _Mask_ you are looking for. 

> the ability to define a CustomSVGMask
You think this more like pass some values to customize or directly pass a new _Component_? I put the focus here, because the mask is an svg composition, in order to allow interaction with the _highlighted_ elemente without duplicating it.


>A use case I have for this is an element which is out of the main document flow and so reactour's default mask, understandably, ignores it.

@MJeorrett  you mean in a _Portal_?

**Comment by MJeorrett** [comment]
Hey @elrumordelaluz, thanks for getting back.

Specific case we have is we are using the [search module](https://react.semantic-ui.com/modules/search/) from semantic ui.  I'm not sure specifically what you mean by `Portal` but the result I am getting is that the greyed out area cuts off / ignores the results list like so:

<img src="https://user-images.githubusercontent.com/9042089/96857118-879eb400-1456-11eb-87c5-45158bf23013.png" alt="search results obscured" width="400">

I guess that this is because the results element has `position: absolute`.

My thinking was is that if there was an extensibility point to allow defining the greyed out area (I called this "mask" but maybe portal is correct term) as an arbitrary SVG element (which I think is what the OP is suggesting), this would allow covering many different scenarios where reactour can not infer where to draw the mask / portal automatically.

**Comment by elrumordelaluz** [comment]
hey @MJeorrett thanks for the details provided. That situation could be solved by _observables_.

Mind creating a reduced reproduction in a `sandbox` so, in case is doable show you how to achieve?

Thanks,

**Comment by MJeorrett** [comment]
Thanks again for the super quick response @elrumordelaluz!

Here is a minimal repro: https://codesandbox.io/s/reactour-semantic-ui-search-repro-v7t68.

**Comment by elrumordelaluz** [comment]
@MJeorrett you could do something like [this](https://codesandbox.io/s/reactour-semantic-ui-search-repro-forked-tynzs)

```js
highlightedSelectors: [".results"],
mutationObservables: [".results"],
resizeObservables: [".results"]
```

**Comment by MJeorrett** [comment]
Awesome, thanks for this @elrumordelaluz, looks to be heading in the right direction.  Is there any documentation on these features?  As far as I can see the documentation is just the README in the repo but maybe I am missing something?  If there is no documentation on this yet then I am happy to dig through the code to understand it and put up a PR for adding to the README if that is desirable?

**Comment by elrumordelaluz** [comment]
Absolutely welcome PRs, and more regarding `docs` that is a big missing part in this project!

**Comment by MJeorrett** [comment]
I looked in to adding documentation @elrumordelaluz and realise my mistake now: the master branch does not reflect the current published version of the project, as is noted with a prominent warning at the top of the README on master!!  The README on the v1 branch includes documentation of these features and so no PR required.  Once you get master back in sync with the published version it will prevent other people making the same mistake as me, though you do have the warning there at the moment on master so not sure what else you can do at the moment.

Great project, and once again MASSIVE thanks for your help!

**Comment by elrumordelaluz** [comment]
no problem! I am happy that everything works well at the end. In the future I want to improve docs but outside the _README_. For now it's ok. Thanks again!

**Comment by haxxxton** [comment]
Hi @elrumordelaluz, heres a couple of redacted screenshots that im trying to emulate. The key thing here is the 'glow' effect around the area. In the first screenshot you'll also note that the mask has rounded top borders, but not on the bottom.

![image](https://user-images.githubusercontent.com/743105/97065260-a7b5ab00-15ef-11eb-911e-8126c66fa9f8.png)
![image](https://user-images.githubusercontent.com/743105/97065320-efd4cd80-15ef-11eb-961c-9a6c2009da8d.png)

**Comment by elrumordelaluz** [comment]
Thanks @haxxxton to share your _use case_. 

Regarding the glow you could solve fast in some using `disableInteraction` prop and customizing the `rect`. Here is an [example](https://codesandbox.io/s/reactour-demo-template-live-forked-og417?file=/styles.css).

**Comment by elrumordelaluz** [comment]
Due to inactivity and the fact that in `v2` all components are more customizable, I am closing this _issue_, but feel free to re-open or create a new one in any case.
