### ISSUE TITLE
More documentation on the observer functionality

### ISSUE THREAD

**Issue by danloiterton** [elrumordelaluz/reactour#32]
Hi there,

fantastic module! Great job.

I'm trying to figure out how you get the observer working, like in the last example of the demo. I have a similar use case where I'm highlighting a button but I want to change the focus to a drawer that gets displayed if the user clicks the button.

I tried adding a selector for the drawer in the 'observer' property but this doesn't seem to do anything. Some clarification on the feature would be grand :)

**Comment by elrumordelaluz** [comment]
hey @danloiterton, thanks for your kind words, I'm happy you are enjoying the _Tour_ 😄 

You are absolutely right, this and other `props` needs more _Documentation_. I'm planning to improve those aspects in the next major version of the _Tour_.

However, you have to point the `observer` into a parent element.

Give an eye in the _Demo_ where the [`observer`](https://github.com/elrumordelaluz/reactour/blob/master/src/demo/App.js#L154) is pointing to a [parent element](https://github.com/elrumordelaluz/reactour/blob/master/src/demo/Demo.js#L123) of the [button](https://github.com/elrumordelaluz/reactour/blob/master/src/demo/Demo.js#L188) and the [section that will appear](https://github.com/elrumordelaluz/reactour/blob/master/src/demo/Demo.js#L193) after `click`.

Please let me know if that works for you.

**Comment by danloiterton** [comment]
Hi @elrumordelaluz, cheers for the reply. So I must just be doing something daft. I still can't get it to work. maybe some code helps:

```
class LayersPanel extends React.Component {
   render() {
      return (
         <div tour="layers_button--observe">
            <IconButton onTouchTap={this.handlePanelToggle}>
               <LayersIcon tour="layers_button"  />
            </IconButton>
            {this.renderPanel()}
         </div>
      );
   }

   renderPanel() {
      let { open } = this.props;

      return (
         <Drawer width={320} open={open}>
             [etc...]
         </Drawer>
      );
   }

   handlePanelToggle = () => {
      const { dispatch } = this.props;
      dispatch(toggleOptions());
   };
}

[map state to props, etc...]
```

The button is highlighted nicely, I can click it and it opens the drawer as usual, but the highlightling doesn't change at all (the button remains highlighted).

Note I'm using a material-ui Drawer and redux handles the 'open' state. 

Am I missing something silly?

**Comment by sheminusminus** [comment]
@danloiterton From the way this component works, I'm thinking it has to be a valid DOM selector, which the `tour` attribute isn't. Does it work if you try it with something like `id='someId'`?

**Comment by elrumordelaluz** [comment]
@danloiterton as @sheminusminus said:

> Looks like it's using the MutationObserver API, which will only look for actual DOM changes. 

and the `Drawer` _Component_  seems to be present in the DOM yet as an empty `div`

**Comment by danloiterton** [comment]
Ahh, ok. Thanks both. If If I actually conditionally render the drawer instead of letting it unhide itself using the 'open' attribute then I can (kind of) get it to work. As you both rightly point out, the MutationObserver doesn't seem to observe css changes. Thanks for the clarification

**Comment by PabloGracia** [comment]
Hi there, 

I'm having also some doubts regarding this feature, and since it's mostly regarding to documentation (this issue is about it) and the issue is still open, I will use it to post my question as well. If you'd rather have me opening a new issue for this, please let me know. 

As I've been reading in the open issues, the "observe" should be pointing to a **parent** of the trigger, and then reactour will focus on the component in that parent that is being rendered as a consequence of the action of the trigger, such as the extra buildings that appear on the Demo (correct me if I'm wrong up to here). 

I'm trying to do something similar with buttons and popovers of the blueprint library, but I'm unable to make it work for this case. For example, I have the following menu that pops up when clicked:
```
<Popover>
  <Button data-tut="reactour__openMenu" />
  <ButtonGroup>
    {A bunch of other buttons in here}
  </ButtonGroup>
</Popover>
```
The target of the popover is the button, whereas the content of the popover is the buttonGroup. Reactour correctly focuses on the button with the data-tut property, however, how can I set my "observe" such that when the button is clicked, the content of the buttonGroup is focused? According to what I've read, I should set a `data-tut="reactour__openMenu--observe"` property in `Popover` but this leads to an error of not finding a node; and if I wrap the popover in a div, and set said property in the div, it does nothing (since it can't _observe_ that there have been changes to the DOM). Can reactour target this, or I should try to look for some workaround to it?

Thank you a lot, and I have to say that reactour is great!

**Comment by elrumordelaluz** [comment]
Hi @PabloGracia and thank you for your detailed _issue_. I think is the right place to post is, as I think is still bad documented.

Regarding your use-case could you pleas make a simple reproduction in a [sandbox](https://codesandbox.io/s/6z56m8x18k?module=%2FApp.js) to give it a try and solve in first place your case, but also helps understand the missing parts in the communications regarding this specific `prop` of the _Tour_.
Thanks,

**Comment by PabloGracia** [comment]
Hi @elrumordelaluz , sorry for the late reply. First of all, thanks for your quick reply on my post. I've created a small reproduction of what I'm trying to achieve in this [sandbox](https://codesandbox.io/embed/winter-mountain-eryt1). 

It consists of two buttons that once clicked pop up two menus with different buttons the user can interact with. As you can see the tour focuses greatly in the buttons as that's how they are described in the steps. However, I can't manage to focus on the pop-up of the second button once this is clicked, _no matter where I place the `--observe` tag_. In some other posts you mentioned that it should be in the parent whose content changes in reaction to a trigger; however, if I place it in the `li` it has no action at all, whereas if I place it in the `Popover`, it just crashes as it is not recognized as a node. 

Do you think the `observe` property can work with these `Popover`s from blueprintjs?

Thank you

**Comment by elrumordelaluz** [comment]
Hi @PabloGracia, thanks for the demo. As you exposed, yes, the `observer` should be a parent of the _DOM_ element that will mutate. In your case, the _Popovers_ seems to be a `portal`, so the _Observer_ couldn't track any changes. 

It's a perfect example to enhace the _observe_ functionality to track elements outside the _MutationObserver_ capabilities, maybe setting a `ref` to listen, or similiar apporaches.
