### ISSUE TITLE
aria-label not showing up in DOM using closeButtonAriaLabel

### ISSUE THREAD

**Issue by chrisfoster22** [elrumordelaluz/reactour#326]
I'm trying to attach an `aria-label` attribute to the close button using the `accessibilityOptions` object. This doesn't seem to be working. When I look at the demo for `reactour` I'm also not seeing the `aria-label` attribute on the close button. [This PR](https://github.com/elrumordelaluz/reactour/pull/222/files) seems to indicate that the attribute is there by default. I've attached an image of the close button in the `reactour` demo.
<img width="1002" alt="Screen Shot 2021-02-12 at 11 51 18 AM" src="https://user-images.githubusercontent.com/10407285/107797506-029f1980-6d29-11eb-985a-57db7ffe5f36.png">

**Comment by rhasselle** [comment]
I'm also still seeing this issue in 1.18.4
`aria-label` is not applied to the close button when specifying `closeButtonAriaLabel` in the `accessibilityOptions`.

Interestingly, if you manually build the `/dist` folder using `rollup` provided in the source files, the issue gets fixed, however this isn't a great solution because every time you install or update the npm, it will get overwritten by the default `/dist` files `reactour.cjs.js` and `reactour.esm.js` which has this error present.

**Comment by elrumordelaluz** [comment]
Thank you @chrisfoster22 and @rhasselle to pointing this, should be fixed on `v1.18.5`.
