### ISSUE TITLE
Can selectors be specified for dom objects that are outside an iframe 

### ISSUE THREAD

**Issue by JoshuaeKaiser** [elrumordelaluz/reactour#328]
Can selectors be specified for dom objects that are outside an iframe? 

Unsure what the lib is doing under the hood, but can we specify the document object that the selector code in run on so that I could for example run the tour code in an iframe but target elements that are outside in on the parent document (same origin policy allowing of course)

**Comment by elrumordelaluz** [comment]
Hi @JoshuaeKaiser, thanks for open the _Issue_ and sorry for the late reply.
It suppose to work, but I expect some issues with calculations. Since the `rect` values for the _Popover_ and _Mask_ comes from the `target`, but if it is inside the `iframe`, the values used won't match with those shown in the _Tour_.

Hope is a little clear, however will make a demo sandbox to show you the issue.
