### ISSUE TITLE
[Bugfix/Improvement] Step observers break everything in test env

### ISSUE THREAD

**Issue by sheminusminus** [elrumordelaluz/reactour#33]
Current behavior:
- `TourPortal` tries to access `MutationObserver` in all envs, which throws a `ReferenceError: MutationObserver is not defined` in test.

Expected/desired behavior: 
- Should only access the `MutationObserver` API if it's available (i.e. we're in a browser). Users of the component could do this for every defined step and/or tour (we're currently doing `observe: global.MutationObserver ? '#elementSelector' : null,`), but it seems much simpler if the component only accesses APIs that are available.

**Comment by sheminusminus** [comment]
(Love the component btw; it's nice to see someone give react-joyride a run for its money finally.)

**Comment by elrumordelaluz** [comment]
hey @sheminusminus thanks for the _Issue_ and for the great words.

You are absolutely right. Each day I'm more convinced that the `observe` API needs improvements. 
As you can see in #32, not only lacks of _Documentation_, also not covers all situations/needs.

Yes I think could be a simple fix what you are describing as the expected behaviour. I'll take a look asap, also [PR](https://github.com/elrumordelaluz/reactour/compare) super welcome!

However I am evaluating the _use-cases_ to think how will be this API in the next major version (also thinking if removing it, what do you think?)

>  it's nice to see someone give react-joyride a run for its money finally.

Didn't understand at all this ⬆️ sentence but yup! 🎉
