### ISSUE TITLE
[BUG] Inconsitent behavior with Material UI Menus

### ISSUE THREAD

**Issue by RonLek** [elrumordelaluz/reactour#330]
On having Tour focus on a MenuItem within a [Menu](https://material-ui.com/components/menus/#menus), even though the shape of the highlighted area comes out to be correct but it becomes mispositoned. On moving to the next step (or pressing the left/right arrow keys in case of a single step) the highlighted area becomes correct.

Here's a CodeSandbox I created - https://codesandbox.io/s/competent-proskuriakova-fjv6j?file=/src/App.js

The highlighted portion is placed well below the Create Community menu item. On pressing the left/right arrow key it takes up the correct position.

**Comment by RonLek** [comment]
@elrumordelaluz am I missing something? Could you please take a look?

**Comment by elrumordelaluz** [comment]
Hi @RonLek, thanks for open the _Issue_.

As I see the Material UI [Menu](https://material-ui.com/api/menu/) has a transition when opening and due to this, probably the _Tour_ is opening before the _Menu_ gets its last position, making calculations for the `step` wrong.

I can get working passing the `setCommunityTourOpen` into `onEnter` Menu's prop, something like:

```jsx
<Menu
  onEntered={() => setCommunityTourOpen(true)}
  // ...
/>
```
[Here is the working sandbox](https://codesandbox.io/s/icy-surf-oegcg?file=/src/App.js)

Don't know if could fit your needs in the real App, but for this demo seems ok. 
Let me know.

**Comment by RonLek** [comment]
That's awesome! I didn't think the transition was creating a problem. I thought it was more because I wasn't using `oberve` the right way. Thanks @elrumordelaluz!
