### ISSUE TITLE
Use the TourProvider outside the root app

### ISSUE THREAD

**Issue by kodekaboom** [elrumordelaluz/reactour#388]
Hi, there is some example that uses the TourProvider outside the root of the app? I'm trying to use the beforeClose and I can't if I use the provider on the root, and there is a prop to disable the tour close when we click mask? I only want to close the tour when I click the x

**Comment by elrumordelaluz** [comment]
Hi @kodekaboom,

> there is some example that uses the TourProvider outside the root of the app

You can position your _TourProvider_ wherever you want, just consider that you can control the _Tour_ through `useTour` hook only on components down this part of the tree.

> I'm trying to use the beforeClose and I can't if I use the provider on the root

Please share an example because on my end works as expected.

> there is a prop to disable the tour close when we click mask?  I only want to close the tour when I click the x

Sure, you can combine [onClickMask](https://github.com/elrumordelaluz/reactour/tree/master/packages/tour#onclickmask-clickprops-clickprops--void) and [disableKeyboardNavigation](https://github.com/elrumordelaluz/reactour/tree/master/packages/tour#disablekeyboardnavigation-boolean--keyboardparts) to obtain what you are looking for. Something like:

```jsx
<TourProvider
  steps={steps}
  disableKeyboardNavigation={["esc"]}
  onClickMask={() => {}}>
  {/* ... */}
</TourProvider>
```

[Here](https://codesandbox.io/s/reactour-tour-demo-using-react-modal-forked-b1ugo?file=/components/App.js:195-380) is a sandbox containing all the use-cases you described.

**Comment by kodekaboom** [comment]
Hi @elrumordelaluz , I put the tour provider outside of the root, its works but now when i move between pages the tour goes to the first step again, another thing is when I added to the root, the tour makes the app goes blank for a sec.

**Comment by elrumordelaluz** [comment]
Could you please share a minimal reproduction of the issue in a sandbox? Thanks
