### ISSUE TITLE
Custom helper

### ISSUE THREAD

**Issue by Ovaideanu** [elrumordelaluz/reactour#391]
Hello guys.
In version 1 we could add a custom helper trough `CustomHelper` prop. How can I add a custom helper with the new approach `TourProvider`?

Thanks!

**Comment by elrumordelaluz** [comment]
[ContentComponent](https://github.com/elrumordelaluz/reactour/tree/master/packages/tour#contentcomponent-componenttypepopovercontentprops) is now available in `@reactour/tour@2.6.0`. [Here](custom-popover-content) is the demo.

Since `@reactour/tour@2.5.0` it is also available the [components](https://github.com/elrumordelaluz/reactour/tree/master/packages/tour#components-popovercomponentstype) prop to customize each Component inside the _Popover_. [Here](https://reactour.vercel.app/#custom-components) is the demo.
