### ISSUE TITLE
TypeScript error in .../node_modules/@reactour/tour/src/types.tsx

### ISSUE THREAD

**Issue by avivm** [elrumordelaluz/reactour#406]
First of all thanks for a great library!

I have upgraded to the new scoped package and receive the following error:

TypeScript error in .../node_modules/@reactour/tour/src/types.tsx(110,10):
Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.  TS1205

    108 |   hideArrow?: boolean
    109 | }
    110 | export { Position }
        |          ^
    111 |

I cannot disable the isolated modules flag:
The following changes are being made to your tsconfig.json file:
  - compilerOptions.isolatedModules must be true (implementation limitation)

skipLibCheck also not working as it is not a d.ts file.

It should be easily fixed with:
`export type { Position }`

Thanks!

**Comment by danilowanner** [comment]
Hey @avivm 

Could it be that you are accidentally including your node_modules in your TS-build? Since you should not actually reference any files in the `@reactour/tour/src` (since this is the source code, as a consumer you would be loading the built version at `dist/index.js` and typings from `dist/index.d.ts`).

Check your package's tsconfig file, specifically the `include` and `exclude` options. This will also greatly improve your build time. More details here: https://github.com/microsoft/TypeScript/wiki/Performance#specifying-files

I hope you can resolve the issue with the above.

**Comment by elrumordelaluz** [comment]
Closing, but feel free to re-open in any case.
