### ISSUE TITLE
Reactour Playground in v3

### ISSUE THREAD

**Issue by shubhrasachdev** [elrumordelaluz/reactour#505]
Hi @elrumordelaluz!

Thanks for this library, it is working out really well for me, great work!

I was just wondering, does the older playground deployment with code snippets and examples live somewhere currently? Because from what I can tell, [https://reactour.vercel.app/](https://reactour.vercel.app/)  seems to have the playground that we used to have earlier (I believe V1) with some updates.

I personally preferred the previous one as opposed to the current one. It was really helpful to understand how the library works, especially when you want to play around with different features and configurations.

**Comment by elrumordelaluz** [comment]
Hi @shubhrasachdev, thanks for open the _Issue_.

There is a version [here](https://reactour.js.org/tour) for the tour, and also for the other components (`mask` and `popover`) changing the route on the url. Those are however a temporary demos, since I have to work a little more to improve `code` on each example.

**Comment by shubhrasachdev** [comment]
Oh okay, I see. This helps in the meantime, thanks for sharing!

**Comment by elrumordelaluz** [comment]
I am closing this _issue_, but feel free to re-open or create a new one in any case.
