### ISSUE TITLE
highlightedSelectors not working

### ISSUE THREAD

**Issue by Gega97** [elrumordelaluz/reactour#510]
[](https://codesandbox.io/s/tour-with-data-fetching-forked-kq69n?file=/src/index.js) When reviewing that example left in the issue [](https://github.com/elrumordelaluz/reactour/issues/418) when I remove the middle element from the selection, it continues to mark everything.

![Screenshot from 2022-10-03 21-16-33](https://user-images.githubusercontent.com/41912617/193713833-5ea4a7e5-c152-4247-b566-60660bf53c08.png)

**Comment by elrumordelaluz** [comment]
Hi @Gega97, thanks for open the _Issue_.

Mind linking the related sandbox? Thanks!

**Comment by Gega97** [comment]
https://codesandbox.io/s/tour-with-data-fetching-forked-kq69n?file=/src/index.js @elrumordelaluz

**Comment by elrumordelaluz** [comment]
The reason is because the _Mask_ is always an unique square. The calculations for `highlightedSelectors` is the result of the bounding square of the `selectors`, so in the case the first and the third element are active, the second one doesn't change the result. But when you have for example, the first one, turned off, the second button state changes the final calculations.

I updated the sandbox to show more clear the behavior.


https://user-images.githubusercontent.com/784056/193822730-4589e723-0500-47a5-b0eb-2f1adc07a071.mp4

**Comment by elrumordelaluz** [comment]
I am closing this _issue_, but feel free to re-open or create a new one in any case.
