### ISSUE TITLE
Idea: Replace Observer with something like AutoSkip

### ISSUE THREAD

**Issue by PetrykowskiM** [elrumordelaluz/reactour#56]
# Summary
As far as I understood, the actual intention of the `observer` function is to let the display move to a new object. 
I think it mostly makes sense for the user to also provide new content in the Tour-Card after the change. 

# Example Step

```
[
  {
    selector: '[data-tour="my-first-step"]',
    content: 'First Step',
    position: 'top',
    autoSkip: true
  },
 {
    selector: '#nextStep',
    content: 'First Step',
    position: 'top',
  },
]
```

If `autoSkip` set to `true`, go to next step when a node '#nextStep'  appears in the DOM.

**Comment by elrumordelaluz** [comment]
Interesting @PetrykowskiM. 

First of all thanks for the interest in improve the API with your proposal.
Im so interested in improve the `observe` part of the _Tour_.

Let me know if I understand well.
So the `step` with `selector: '#nextStep'` should be ignored in the regular navigation, right?

In any case you should declare the `parent` node which will be _Observed_.

**Comment by PetrykowskiM** [comment]
No it should not be ignored. By defining `autoSkip: true` reactour should look for the next step's selector to exist.

If the next Selector exists in the DOM, the tour automatically goes to the next step.

Maybe this example could make it clear: [Sandbox Example](https://codesandbox.io/s/526n1ykk2k)

**Comment by elrumordelaluz** [comment]
ok, in that case you are taking advantage of two things:
- hidding the mask to allow interact with elements bellow
- not found `DOM` node that renders the _Step_ centered

right?

One of the initial needs, shown in the [Demo](https://elrumordelaluz.github.io/reactour/), was to _highlight_ that button (in your, the "Open menu" one), letting _interact_ and the _highlight_ the changes.

Useful when introducing a _feature_ with _subfeatures_, like "look here is the button to launch something; then, look that something".

Let me know if make sense, and if you think could be achieved the same behaviour (_highlight_ + _interact_) with your proposal.

**Comment by PetrykowskiM** [comment]
Yeah, hiding the mask would be an additional feature. But yeah, that would definitively make sense for this use case.

Can you try to explain your alternative approach in more detailed? Otherwise I cannot tell whether it also covers the usecase.

**Comment by elrumordelaluz** [comment]
> Yeah, hiding the mask would be an additional feature.

It's absolutely valid what you've done to hide the _Mask_ since you could also set the `maskClassName`. Don't know if it's necessary a `prop` to hide it, since in most cases is useful to _highlight_ the desired element.

What I mean with _the initial needs_ for the `observe` feature is what you could see in the last step of the [demo](https://elrumordelaluz.github.io/reactour/) where the `element` is _highlighted_ (the mask covers all except that element) but also available to interact, so when _click_, since is an _observed_ `step`, the _focus_ moves into the new elements.

![reactour](https://user-images.githubusercontent.com/784056/42379776-205645fc-812c-11e8-83aa-3d16807d8377.gif)

**Comment by PetrykowskiM** [comment]
That would also be doable by implementing `autoskip`.

**Comment by jasan-s** [comment]
@PetrykowskiM @elrumordelaluz  i am also bit unclear about observe. even after looking at the demo. is the selector based in the observe just to see if new elements are added to DOM? and if so move the focus to them? I wanted the behavior of going to the next step if and only if user clicked the button in the dom.

**Comment by elrumordelaluz** [comment]
hey @jasan-s, thanks for the _idea_, is absolutely valid! 
The _Observe_ behaviour tracks (observes) changes into the element passed to the `prop` (generally a parent of the `step` element) and when changes happen, the `step` _highlightes_ the new part instead of the `elem` passed originally.

Let's iterate to make the idea of this _issue_ happen.
