### ISSUE TITLE
[IE] css variables are not supported in internet explorer

### ISSUE THREAD

**Issue by audrium** [elrumordelaluz/reactour#6]
Hey,
thanks for your amazing component!
Everything works perfectly fine (even on IE), but I noticed that when I set --reactour-accent to different color it is not working in IE. I'm talking about this line:
https://github.com/elrumordelaluz/reactour/blob/58d391b0c3dc065d81b5e5791b0eba72d3ef0395/src/components.js#L24
Googled that css variables are not supported in IE:
https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables
Is there any other way to change the color?

**Comment by elrumordelaluz** [comment]
Hey @audrium, thank you! 

You are absolutely right, I'm sorry for that. 
Anyway you could [set](https://github.com/elrumordelaluz/reactour#proptypes) the `className` for the _Helper_ Component and customise the styles.

For example, in the [demo](https://github.com/elrumordelaluz/reactour/blob/master/src/demo/App.js#L41-L46) we set the class as `.helper` so in my _stylesheet_ could add something like this 👇 to change the _current_ number badge:
```
.helper:after {
  background-color: #bada55;
}
```
For the navigation _Dot_ Component is a little bit trickier, since we don't add a `className` directly (If you are working on and feels is necessary to add a `className`, absolutely appreciated a PR) you could do something like:

```
.helper nav > button:disabled {
  color:  #bada55;
}
```

Keeping in mind that you are using tag selectors so have to pay attention in the content you put inside the _Helper_ Component (in this case, avoid add markup like a `nav` with inside a `button:disabled`.

Hope this helps and fix your issue in IE, happy to know that the rest works well in this browser!

**Comment by audrium** [comment]
thanks @elrumordelaluz ! this solved my issue. Cheers!

**Comment by elrumordelaluz** [comment]
perfect! let me know if there's any other thing.

And obviously if you put `reactour` in a public website! 🙏
