### ISSUE TITLE
It's unable to modify navigation styles

### ISSUE THREAD

**Issue by dannicsitnikov** [elrumordelaluz/reactour#610]
Hi there! Im faced with an issue. At example below I passing a css properties to navigation but they are didn't applying. And `console.log(base)` didn' t log. Why the reason?

`styles={{
        navigation: (base) => {
          console.log(base)
          return {
            ...base,
            justifyContent: 'flex-end !important',
          }
        },
      }}`

**Comment by elrumordelaluz** [comment]
Hi @dannicsitnikov, thanks for open the _Issue_.

Mind creating a minimal reproduction in a sandbox in order to allow others to debug faster your use-case and try to find a solution as soon as possible? 

[Here](https://codesandbox.io/s/dry-butterfly-zmn2zk) is an example based on your `styles`.

Probably you are looking into `controls` [styles](https://docs.react.tours/tour/props#styles) key. Take a look into the [custom styles example](https://docs.react.tours/tour/examples#custom-styles)

Thanks!

**Comment by dannicsitnikov** [comment]
@elrumordelaluz ah, so sorry. Yes, you're right. Thanks a lot!
