### ISSUE TITLE
Add a border color to the Highlighted area

### ISSUE THREAD

**Issue by rezarezash** [elrumordelaluz/reactour#633]
Hello, could you tell me how I can add a border with color to the highlighted area, please? None of the below combinations works for me

```js
root.render(
    <TourProvider steps={steps} styles={{
        control: (base) => ({
            ...base,
            border: '2px solid red',
        }),
        maskWrapper: (base) => ({
            ...base,
            border: '2px solid red',
        }),
        maskRect: (base) => ({
            ...base,
            border: '2px solid red',
        }),
        highlightedArea: (base) => ({
            ...base,
            border: '2px solid red', 
            outlineOffset: '5px',
        }),
        badge: (base) => ({ ...base, color: 'black', background: '#e0aa3e' })
    }}>
        <App />
    </TourProvider>
);
```

**Comment by elrumordelaluz** [comment]
Hi @rezarezash, thanks for open the _Issue_.

You can do this using `svg` props instead of `border` or `outline`, since the mask is svg-based. Something like:

```js
<TourProvider
      steps={steps}
      styles={{
        highlightedArea: (base) => ({
          ...base,
          stroke: "#e0aa3e",
          strokeWidth: "2px",
          display: "block",
          pointerEvents: "none",
        })
    }} />
```

Remember to show this part using `display: block` (since is hidden by default) and allow clicking/interacting with the elements below using `pointerEvents: "none"`.

[Here](https://codesandbox.io/p/sandbox/thirsty-david-gnqzpd?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clx07pgbh00073b6glvgkaikw%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clx07pgbh00033b6gm820ep9s%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clx07pgbh00043b6gbz2t8szx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clx07pgbh00063b6g50hy8dwb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clx07pgbh00033b6gm820ep9s%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx07pgbh00023b6gq4omeq3o%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A22%252C%2522startColumn%2522%253A11%252C%2522endLineNumber%2522%253A22%252C%2522endColumn%2522%253A11%257D%255D%257D%255D%252C%2522id%2522%253A%2522clx07pgbh00033b6gm820ep9s%2522%252C%2522activeTabId%2522%253A%2522clx07pgbh00023b6gq4omeq3o%2522%257D%252C%2522clx07pgbh00063b6g50hy8dwb%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx07pgbh00053b6gqljemhlr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clx07pgbh00063b6g50hy8dwb%2522%252C%2522activeTabId%2522%253A%2522clx07pgbh00053b6gqljemhlr%2522%257D%252C%2522clx07pgbh00043b6gbz2t8szx%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clx07pgbh00043b6gbz2t8szx%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) is a working example.
