### ISSUE TITLE
Enable scroll while keeping mask on fields

### ISSUE THREAD

**Issue by mateuswolkmer** [elrumordelaluz/reactour#80]
So I have a problem where I want to use the tour in a web page that can be used in mobile. Although, the form in one if my steps is bigger than the screen, I have to scroll to be able to see it all. It happens in desktop if the screen isn't that big also.
I see that when the tour is active, scrolling is disabled on body. Although, if I enable it again in styles, I can scroll but the mask stays still. Is there a way to make the mask move with the content when scrolling, keeping the right div focused with the mask?

**Comment by elrumordelaluz** [comment]
hi @mateuswsouza thanks for the _issue_ and interest on _Reactour_.

It is interesting your _use-case_, and could be possible to attach the `showStep` function (debounced) to `scroll` event, like what we do with [resize](https://github.com/elrumordelaluz/reactour/blob/master/src/TourPortal.js#L165), however will result in a conflict, since the same method try to [scroll](https://github.com/elrumordelaluz/reactour/blob/master/src/TourPortal.js#L261) the `element` into view. A possible implementation, but not conviced me at all could be to disable that _scrollIntoView_ behaviour when `scroll` event is attached.

Regarding the big step content, you are absolutely right, a possible way could be to calculate the `height` and limit to viewport limits, letting the inner content scroll.

In case you hace a [sandbox](https://codesandbox.io/s/6z56m8x18k?module=%2FApp.js) or a repo with examples would be fantastic, to check, analyse and try to implement any solution.

**Comment by mateuswsouza** [comment]
No problem, thank you for the awesome tool.

I'm using it in a professional project and I'm kinda running against time right now, so I will possibly have to deal with this by disabling tours in mobile or doing it in a way that the tooltip appears at the top of the screen but no mask appears.
Let me know if you or someone else implements this enhancement soon so I can make it work in my project. :) Otherwise, I will have more time after december and will possibly try to do it if it's not there yet. Keep this issue updated!

**Comment by mateuswsouza** [comment]
**Update:**
As I said, I don't have much time to invest to make a suitable contribution to the repo yet, but I did forked it and made some changes exclusively for my project and want to share them as a possible temporary solution for big selected targets like forms, as in my example,

What I did is I made it so it is possible to scroll during the tour, but when you scroll the mask disappears and the helper stands still. I've done that by changing **onAfterOpen** to:  
> onAfterOpen: () => {
>     //   document.body.style.overflowY = 'hidden' 
>     // Scroll enabled, but when scrolled, the mask will turn invisible 
>       window.onwheel = () => document.querySelectorAll('.tour-mask')[0].style.display = 'none'
>     },

And then, the method **showStep** turns it back visible (for when you change steps):
> showStep = () => {
>     // Mask returns to be visible
>     document.querySelectorAll('.tour-mask')[0].style.display = null;
>     ...

Also, I've set the offset to be just bellow my website header + the helper height, so it is nicely positioned in the top of the screen.
_I had to remove all graphics to preserve my project, but you can have an idea_ : [Example](https://i.imgur.com/XwJfPFE.gif)

**Comment by adamcoulombe** [comment]
> It is interesting your _use-case_, and could be possible to attach the `showStep` function (debounced) to `scroll` event, like what we do with [resize](https://github.com/elrumordelaluz/reactour/blob/master/src/TourPortal.js#L165), however will result in a conflict, since the same method try to [scroll](https://github.com/elrumordelaluz/reactour/blob/master/src/TourPortal.js#L261) the `element` into view. A possible implementation, but not conviced me at all could be to disable that _scrollIntoView_ behaviour when `scroll` event is attached.

I am trying to attach a `showStep` function to the scroll event, but I dont see how I can do that? How to I expose that method so I can do it from a scroll event handler

**Comment by elrumordelaluz** [comment]
I think I mean the `showStep` internal method, not exposed.
