### ISSUE TITLE
overflow-y: hidden; not added to body since 1.10.0

### ISSUE THREAD

**Issue by didil** [elrumordelaluz/reactour#92]
It work with 1.9.1 but scrolling is not prevented anymore since 1.10.0

**Comment by elrumordelaluz** [comment]
@didil yes, I'm sorry I missed to update the _Documentation_.

Since there were some [issues](https://github.com/elrumordelaluz/reactour/issues/10) related on this cross-plattform, the idea is to remove the default in `onAfterOpen` and `onBeforeClose` letting the end user to implement based on needs. 

You could still apply the same as before simply passing
```js
<Tour
  onAfterOpen={() => { document.body.style.overflowY = 'hidden' }}
  onBeforeOpen={() => { document.body.style.overflowY = 'auto' }}
  ...
/> 
```

However I encourage you to keep an eye into the [demo](https://github.com/elrumordelaluz/reactour/blob/master/src/demo/App.js#L55-L56) which implements the same behaviour using [body-scroll-lock](https://github.com/willmcpo/body-scroll-lock) to avoid cross-plattform issues.

**Comment by didil** [comment]
Thanks ! your probably mean onBeforeClose not onBeforeOpen
